import React from 'react';
import ReactDOM from 'react-dom'


const ccaDATA = [
" Flag Committee",
"KE Web",
"KE Welcoming Orientation Camp (KEWOC) Committee",
"Peer Support Group (PSG)",
"RAG Committee",
"Merit Awards Board (MAB)",
"Amplitude",
"Chinese Drama",
"Hallplay",
"The Dream Composition (TDC)",
"KE Motion",
"KE Vision",
"The SOCs",
"Yearbook",
"Block Committee",
"Green Team",
"Hall Affairs Board (HAB)",
"KE Angels",
"External Relations Committee (ERC)",
"KEVIIing Back",
"OCIP Cambodia",
"OCIP Laos",
"acaKE",
"BandXY",
"Choir",
"Cultural Management Board (CMB)",
"KE Dance",
"KE Titans",
"KEnsemble",
"Badminton (M&F)",
"Basketball (M&F)",
"Floorball (M&F)",
"Handball (M&F)",
"Netball (F)",
"Road Relay (M&F)",
"Sepak Takraw (M)",
"Soccer (M&F)",
"Softball (mixed)",
"Squash (M&F)",
"Swimming (M&F)",
"Table Tennis (M&F)",
"Tennis (M&F)",
"Touch Rugby (M&F)",
"Track & Field (M&F)",
"Ultimate Frisbee (mixed)",
"Volleyball (M&F)",
"IHG Co-Convening",
"Sports Management Committee (SMC)",
]

export default ccaDATA;